### ISSUE TITLE
Some questions about the results on the simulated data

### ISSUE THREAD

**Issue by ydy1127** [tjblaette/getitd#10]
Hi!

getITD have shown good results on our real data, which are hybridize-captured Pannel data (2x150bp) with ITD length of 6-165bp and location between chr13:28608103-28608324. getITD can accurately detect ITD length of less than 100bp.

However, the performance on the simulated data is far worse than the real data. We used the NGS simulation software wgsim to simulate 500 pairs-end data (2x100bp) at chr13:28607901-28608099 (the starting position of the repeated fragment on the reference genome) with a length of 3-300bp, and a frequency randomly distributed at 5-55%. We found that getITD detected only 101 of these, most of which were ITDs less than 100bp. However, some ITDs with a range of less than 100bp between 28607910 and 28607997 were not detected.

We have added the parameters (-require_indel_free_primers False; -min_read_copies 1; -infer_sense_from_alignment True) in the process of detection according to the question you replied before. May I ask why this situation is the case?

**Comment by ydy1127** [comment]
Hi!

In your earlier reply to me, you mentioned that the default reference sequence range is chr13:28608352:28608023, which means that ITD is detected within that range. So does the start and end of the repeat sequence have to be in this range? Or can it be detected when the repeat sequence partially covers this range?

Looking forward to your reply!

**Comment by tjblaette** [comment]
Hi!

getITD requires that at least one of the repeat tandems is fully sequenced, plus at least 6 bp of the second tandem, which must be covered by the same read. Generally, getITD will only consider sequences mapped to, and contained within, the supplied reference sequence in `anno/amplicon.txt`. This has two consequences:

1) In your 150 bp real data, the longest detectable ITD would be 144 bp long (assuming the site is appropriately covered). The largest detectable ITD in your simulated 100 bp reads is 94 (93 for in-frame) bp long. If you detect longer ITDs than this, could you share a sample or two for me to look at?

2) It is possible to detect ITDs outside of getITD's default target region, but you will have to accordingly extend the reference sequence in `anno/amplicon.txt` and `anno/amplicon_kayser.tsv`. 

Please let me know if you need any help with this!

All the best,
Tamara
