### ISSUE TITLE
Analysis won't complete

### ISSUE THREAD

**Issue by CodingFox25** [tjblaette/getitd#11]
After it finishes reading this FASTQ files it doesn't progress past this point and doesn't give an error to console appearing as if it is still running. 

Python version 3.9.0
Command ran:

python3 getitd.py Sample1 Sample_R1.fastq Sample_R2.fastq

-- Reading FASTQ files --
Reading FASTQ files took 479.1413869801909 s
Number of total reads: 23669948
Number of total reads remainging after N-trimming: 23669946 (99.99999155046729 %)
Mean read length after N-trimming: 149.99926873512936

**Comment by tjblaette** [comment]
Hi there,

At this stage, getITD is checking and filtering read quality before collecting unique read sequences, which takes a very long time when there are this many reads. Are all 24 million reads from the FLT3-ITD target region? If these are reads from a larger panel, I recommend extracting relevant reads first to reduce run time: Align the fastq files using a standard aligner such as BWA and extract relevant reads using SAMtools. Let me know, if you need any help with this, I'm happy to provide more.

I will meanwhile add a note to the output so that it's more clear what getITD is doing at this stage. Thanks for pointing this out!

**Comment by CodingFox25** [comment]
Extracting just the region of interest ran much quicker and produced one of the expected ITDs! Do you know the range of the program’s detection size? I’m interested in one around 93 BPs in size

**Comment by tjblaette** [comment]
So glad it worked for you!

The range of detection depends on your read length. getITD requires that at least one of the two ITD tandems is fully sequenced while the other one has to have at least 6 bp sequenced. That means, for 150 bp reads, the largest detectable ITD would be 144 bp long.

Depending on the assay you are using, there might be a few parameters that need to be adjusted. Is your sequencing data based on target enrichment/hybridization capture or is it amplicon-based? 
- For amplicon-based protocols you will likely need to adjust `-forward_primer` and `-reverse_primer`.
- For target enrichment protocols you need to set `-require_indel_free_primers False -min_read_copies 1`.

You should also check `-infer_sense_from_alignment`: the default value of `False` expects that reads in your R1 read directly map to the reference sequence in `anno/amplicon.txt` while R2 reads will be reverse-complemented and then aligned. When FASTQ files are not sorted in thlis way, you could lose half of your reads during the alignment stage. If in doubt, try running a few samples with both `True` and `False` to compare the results. Set it to `True` for all samples if with this setting you see a much higher number of reads going into the final analysis. (Setting it to `True` should do no harm besides ~ doubling run time during the alignment stage.)

Let me know how it goes and whether there is anything else I can do to help!

**Comment by CodingFox25** [comment]
Thanks for all your help!
I am using hybrid capture so these settings were just what I needed. Analysis ran much smoother this time around.

**Comment by tjblaette** [comment]
Oh perfect, that's good to hear! I'll close this issue then but definitely come back if there is anything else that I can help you with.
