### ISSUE TITLE
possible to use without GUI

### ISSUE THREAD

**Issue by Balthasar-eu** [tjblaette/getitd#12]
Hi, I am interested in using this tool, but I wonder if it is possible to use it without GUI? When I try to launch it it captures all input and blocks any use of my PC but nothing gets displayed.

**Comment by tjblaette** [comment]
Hi there,

which operating system are you using? How did you try to run getITD? 
getITD is actually meant to be used without a GUI; the GUI wrappers are meant to help people who cannot or do not know how to work in the terminal. Example commands for Linux/Mac and Windows are provided in the README.md (see [here](https://github.com/tjblaette/getitd)).

Please let me know whether you need further advice on how to use getITD or in case there is a problem with the examples.

**Comment by Balthasar-eu** [comment]
Hi, thanks for the fast reply!
I use Linux and executed it with: ./getitd.py

**Comment by Balthasar-eu** [comment]
Ah, I see the problem is that there is no shebang in the first line, so I don't even know what it used to execute the tool. Maybe you could add `#!/bin/env python3` to the first line?

**Comment by tjblaette** [comment]
Hi, and thanks for the suggestion. I hadn't considered adding a shebang. Do you know whether this is supported under Windows as well? Due to the pandemic I can only test on Linux right now, as I have no access to Windows/Mac from home. 

Calling the python interpreter explicitly should get you sorted for now, right?

**Comment by Balthasar-eu** [comment]
Thanks. Yes it works by calling the interpreter explicitly.
I am not sure, since I did not use Windows for a long time either, but I think the shebang doesn't work under Windows. However, since it starts with a comment character it is just ignored, so not harmful in any way.

And do you know if this tool can work if the fragment length of the sequencing is less than the length of the ITD?

**Comment by tjblaette** [comment]
getITD requires that at least one ITD tandem is fully sequenced within a given read AND at least 6 bp of the second tandem have to be sequenced as well. If your reads are shorter than the tandems, getITD will not be able to call an ITD. The longest detectable ITD will be your read length - 6bp.

**Comment by Balthasar-eu** [comment]
Okay, thanks a lot!
