### ISSUE TITLE
error 'decimal.DivisionByZero' while running getITD

### ISSUE THREAD

**Issue by jsha129** [tjblaette/getitd#14]
Dear Tamara,
Thank you for developing and maintaining getITD. We routinely use it in our lab now. I have been getting 'decimal.DivisionByZero'. Could you please explain what this means and how to fix it? Error log and output are attached. Happy to share fastq or bam if you like. Many thanks.
Jay
--
python v3.9
getitd_v1.5.13
bwaModule      = 'bwa/0.7.17-gcc5'
samtoolsModule = 'samtools/1.9-gcc5'  
hg19
-- error
Traceback (most recent call last):
  File "/home/jsha0071/cm41/jsha0071/bin/getitd_v1.5.13/getitd.py", line 2219, in <module>
    main(config)
  File "/home/jsha0071/cm41/jsha0071/bin/getitd_v1.5.13/getitd.py", line 2157, in main
    insert = insert.calc_vaf()
  File "/home/jsha0071/cm41/jsha0071/bin/getitd_v1.5.13/getitd.py", line 567, in calc_vaf
    self.vaf = dc.Decimal(self.counts) / self.coverage * 100
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]

-- output
==== PROCESSING SAMPLE X ====
-- Reading FASTQ files --
Reading FASTQ files took 23.48 s
Number of total reads: 2246444
Number of total reads > 100bp remaining after N-trimming: 2246069 (99.98 %)
Mean read length after N-trimming: 150.99
Number of total reads with mean BQS >= 30: 2210110 (98.38 %)
Getting unique reads took 32.92 s

Number of unique reads with mean BQS >= 30: 16020
Number of unique reads with at least 2 copies: 3650
Total reads remaining for analysis: 2197740 (97.83 %)

-- Aligning to Reference --
Alignment took 41.25 s
Filtering 43 / 3650 low quality alignments with a score < 30.0 % of max
Turned OFF indel-free primer filter!
Total reads remaining for analysis: 2193770 (97.66 %)
Calculating coverage took 23.33 s

-- Looking for insertions & ITDs --
Collecting inserts took 1.51 s
1287 inserts >= 6 bp were found
0/1287 insertions were part of adapters and filtered
Filtering inserts for adapter sequences took 0.23 s

**Comment by tjblaette** [comment]
Hi Jay,

I'm very happy to hear that you find getITD useful! It seems there is a problem with the VAF calculation in this sample. If you can share the FASTQ files that you input into getITD so that I can reproduce (and fix) that error, that would be perfect. This is definitely not something that should be happening. 

Thanks for reporting,
and all the best,
Tamara

**Comment by jsha129** [comment]
Hi Tamara,
Thank you for looking into this. What's your email address? I will share a google drive folder containing fastq files with you. Thanks
J

**Comment by tjblaette** [comment]
Hi Jay,

you can email me at my work address.

All the best,
Tamara

**Comment by jsha129** [comment]
Dear Tamara,
I have shared a folder containing the fastq files of a problematic sample
from my work email id ***@***.***).
Thank you again for looking into this. Let me know if I could be of further
assistance.
Regards
Jay

**Comment by tjblaette** [comment]
Hi Jay,

I don't think I got an email from you. Could you resend?

Thanks,
Tamara

**Comment by jsha129** [comment]
Okay. I sent again. Please confirm that you received it. Thanks
J

**Comment by tjblaette** [comment]
Got it!

I will let you know once I find and fix the problem.
Tamara

**Comment by jsha129** [comment]
Fantastic. Thanks again. J

**Comment by jsha129** [comment]
Dear Tamara,
Hope you are doing well. Just touching base on the getITD issue.
Let me know if I can be of any help.
Thanks
Jay

**Comment by tjblaette** [comment]
Hi Jay,
I have some time reserved this week to have a look. I will let you know once I know more.
Haven't forgotten you :)

**Comment by jsha129** [comment]
Hi Tamara,
Thanks again.

**Comment by tjblaette** [comment]
Hi Jay,

it seems your sample contained one long 3' trailing insert that wasn't being handled properly. I've added a fix, v1.5.14, to the develop branch. I will rerun some more of our samples to make sure nothing else is affected by the update before pushing to master, but so far it's looking good. Please let me know if the update fixes your problem or causes any others.

All the best,
Tamara

**Comment by jsha129** [comment]
Hi Tamara,
Thanks very much for fixing the error! much appreciated. Sure, I will let
you know how my test run goes.
Thanks again
J

**Comment by tjblaette** [comment]
Hi Jay,

I just pushed another minor fix to the previous update onto the develop branch. Some sequences with trailing inserts on both ends of the read were creating infinite loops in v1.5.14, causing getITD to fail with a RecursionError. 

All the best,
Tamara

**Comment by jsha129** [comment]
Dear Tamara,
The script from v1.5.15 from the develop branch successfully completed the processing of 5 samples that had raised the error initially. Thank you so much for addressing it :) much appreciated. 
Best wishes
Jay

**Comment by tjblaette** [comment]
Hi Jay,

thank you so much for both reporting the error and confirming the fix!

All the very best,
Tamara
