### ISSUE TITLE
AssertionError when primers included

### ISSUE THREAD

**Issue by ccchyn** [tjblaette/getitd#8]
Hi,

May I ask if you have encountered this issue:
Every time I include my "-forward_primer"and "-reverse_primer" options the following error occurs in the "Looking for insertions & ITDs" section: 

-- Looking for insertions & ITDs --
Collecting inserts took 2.9154222920000166 s
3015 insertions were found
0/3015 insertions were part of adapters and filtered
Filtering inserts for adapter sequences took 1.5396939880000104 s
Traceback (most recent call last):
  File "getitd.py", line 2070, in <module>
    main(config)
  File "getitd.py", line 2021, in main
    insert = insert.calc_vaf()
  File "getitd.py", line 553, in calc_vaf
    assert self.vaf >= 0 and self.vaf <= 100
AssertionError

My primers do differ from the default settings and I am wondering if you have any suggestions to overcome this error? 

Thank you

**Comment by tjblaette** [comment]
Hi,
and thanks for reporting!

I've double-checked passing primers explicitly using the provided test data set and that works fine. It's likely not a problem directly related to the primer arguments themselves. (I'm guessing you are also getting the same error when disabling the primer filter via `-require_indel_free_primers False` regardless of whether you are providing your own primers or not?) 

Could you provide me with a small FASTQ file and the exact command you're using to reproduce the error? I'll look into it then and see what's causing the problem. I'm sure we'll be able to sort it out!

Thanks & a Happy New Year!

**Comment by ccchyn** [comment]
Dear Tamara, 

Thank you for such a quick response!
Yes you are right - I do get the same error when disabling the primer filter as well. 

I tried to attached my fastq files (total 15 mb) but was unable to send through due to the file size (too large?). Do you know how I may send that through to you? 

My code is 
python3 getitd.py -nkern 6 [output] [path to fastq1] [path to fastq2] -forward_primer GCAATTTAGGTATGAAAGCCAGCTAC GCACGTACTCACCATTTGTCTTTG -reverse_primer ATGGAAAAGAAATGCTGCAGAAAC -minscore_alignments 0.3 -require_indel_free_primers False -max_trailing_bp 4

Thank you so much for your help! I also wanted to thank you for developing this brilliant code and making it open source. 
Happy new year and stay safe

Chyn

**Comment by ccchyn** [comment]
[CCtest1_S4_L001_R1_001.fastq.gz](https://github.com/tjblaette/getitd/files/5756431/CCtest1_S4_L001_R1_001.fastq.gz)
[CCtest1_S4_L001_R2_001.fastq.gz](https://github.com/tjblaette/getitd/files/5756432/CCtest1_S4_L001_R2_001.fastq.gz)

Hi Tamara,

Please see example fastq files attached - hopefully you are able to see them.

Chyn

**Comment by tjblaette** [comment]
Hi Chyn,

looks good, I can open both files. Thanks for sending these over, I will have a look later and get back to you once I know more!

All the best,
Tamara

**Comment by tjblaette** [comment]
Hi Chyn,

I have taken a look at the files and noted a few things.

1. Given those files and your command from above, I cannot reproduce the error. See the log attached. Are you using the newest version of getitd?
2. Your command lists three primers. Is there a second reverse primer missing?
3. Many reads are filtered at the alignment stage and you have already decreased the alignment score threshold to 0.3. Base qualities look fine and the three primers given all reside within the default amplicon sequence. Do you know why so many sequences are filtered at this step or is this unexpected? 

All the best,
Tamara
[stats.txt](https://github.com/tjblaette/getitd/files/5770102/stats.txt)

**Comment by ccchyn** [comment]
Hi Tamara,

1. It is so weird that you do not get an error - I was using version 1.5.0 which is the current version. I also re-downloaded the files today and repeated the same code but still got an assertion error code (see attached). Also it seems that the output from "Aligning to reference" reference section is different between mine and yours - do you know why that may be given that we are processing the same files using the same command line / same python code? 
My python version is 3.8.6 -- should I update that? I wonder what else could it be? 

2. I only have one reverse primer

3. I lowered the alignment score to be able to identify more ITDs. I find that sometimes the known ITDs are not called with the default settings (e.g. in this sample case I sent you, I can clearly see an ITD of high VAF in IGV but when I used default settings it was not called in the final merged file". I am not sure why so many sequences are filtered so it is rather unexpected. 


thanks++ for your help
Chyn
[CC_test2_output.txt](https://github.com/tjblaette/getitd/files/5772282/CC_test2_output.txt)

**Comment by tjblaette** [comment]
Hi Chyn,

that is very strange indeed. I will look into it. I don't think it should be the python version, but clearly something is different between your and my run and/or setup. You didn't change the reference file, right? What operating system are you using? (I can currently only test on Ubuntu.)

This is what I ran on my side: [rep_error.txt](https://github.com/tjblaette/getitd/files/5772600/rep_error.txt)
Can you check whether this works for you? 

All the best,
Tamara

**Comment by ccchyn** [comment]
Hi Tamara,

I still get the same exact output and error when following the codes in the rep_error.txt file. 
I am using MacOS Big Sur, didn't change the reference file either. 

Chyn

**Comment by ccchyn** [comment]
Hi Tamara, 

I just tested on another computer using macOS Catalina and also got the same error code too.

Chyn

**Comment by tjblaette** [comment]
Mhhh. I'm not sure what's causing the problem then. Is it this sample only or does this happen for all of your samples? If it happens with all your samples, does it happen with the test data set that comes along with getitd? I did test on a Mac, two actually, right before publication, but this is a while back.

If you provide me with your python package versions I could try reproducing the error with those. However, if that does reproduce the error, I'm not sure it's something to fix within getitd. I'll ask around tomorrow and see if anyone has another idea.

**Comment by ccchyn** [comment]
Hi Tamara, 

it is happening to majority of my samples (~80%). 
I can process the test data - that went OK even with the options I have included. 

My python is 3.8.6
Pandas is 1.2.0
Numpy is 1.19.4
Biopython 1.78
Easygui 0.98.1

So weird. As mentioned, the output from your "aligning to reference" is already different from mine, with half the reads left (345047) for processing as compared to mine (over 601682 reads left). And then the assertion error occurred when trying to assert the VAF ranges. 

I have now tried in on 3 MacOS computers and all three gave me the same error and output. 

Also, when I processed the code without the options, 3 ITDs are found (all <1%), but they are not the one visible on IGV and I know from capillary electrophoresis that there is a reasonably sizeable VAF - could you see that from your output? 

thank you 

Chyn

**Comment by ccchyn** [comment]
Hi Tamara,

I spun up an Ubuntu instance on AWS and I could run the code successfully on the first sample I shared, although the output do differs slightly from yours - stats.txt file attached. 

Nonetheless some samples still end up with an assertion error. I have uploaded another sample here that I could not run on the Ubuntu instance either when the primer options are included (same assertion error).

thanks!

[CCTest2_R1_001.fastq.gz](https://github.com/tjblaette/getitd/files/5775344/CCTest2_R1_001.fastq.gz)
[CCTest2_R2_001.fastq.gz](https://github.com/tjblaette/getitd/files/5775345/CCTest2_R2_001.fastq.gz)

[stats.txt](https://github.com/tjblaette/getitd/files/5775106/stats.txt)

**Comment by tjblaette** [comment]
Hi Chyn,

ok, well I'm very glad it's working on Ubuntu - I was starting to doubt myself. :)

Looking at your stats file from the Ubuntu trial, I think you are only using one of the two FASTQ files? You start with 300k reads instead of the 600k that I have using both files. That is why your stats differ from mine. It also shows us that your R1 FASTQ does not have this problem of too many reads being filtered at the alignment stage - it is only the R2 file. (I have also run them separately to confirm this, see here: 
[stats_r1-only.txt](https://github.com/tjblaette/getitd/files/5775764/stats_r1-only.txt)
[stats_r2-only.txt](https://github.com/tjblaette/getitd/files/5775765/stats_r2-only.txt)

Running them together finds four ITDs, one of which is around 60 bp long with a VAF of 90%. Is that the one you're expecting?

So I think we have two problems here: Firstly, it's not running correctly on a Mac for you, and secondly, half of your R2 reads are not aligned to the reference.

**Comment by tjblaette** [comment]
Just wondering in case the two problems are somehow related: Can you run the R1 and R2 FASTQ files individually on your mac? Append `-infer_sense_from_alignment True` to your command when you do.

**Comment by tjblaette** [comment]
Chyn,
 
I have solved one of the two problems! Apparently this was caused by biopython (see [here](https://github.com/biopython/biopython/issues/1532)) which meanwhile has been solved, though the version on our server wasn't updated. So thank you for raising this issue and sorry for the initial confusion! I can now reproduce your assertion error and will be back once I find out more.

**Comment by ccchyn** [comment]
Thanks Tamara - hopefully it can be solved!

**Comment by tjblaette** [comment]
Hi Chyn,

it looks like I'm getting there. I have fixed the way one of the insert coordinates was calculated, which messed up your VAF to come out at > 100%. Your sample runs through and retains 95% of all reads for me. I will run some tests on our samples to make sure the update doesn't break something else. Hopefully I will be back with an updated version of getITD within the week!

All the best,
Tamara

**Comment by ccchyn** [comment]
Thanks so much Tamara for this. I look forward to the update! 

Chyn

**Comment by tjblaette** [comment]
Hi Chyn,

my first tests were unfortunately unsuccessful, but I'm running another round now. Hopefully I didn't break anything this time. 

Thanks for hanging in there! I've been quite swamped at work but haven't forgotten you.

**Comment by tjblaette** [comment]
I have pushed current edits on the develop branch, in case you'd like to check them out. I'm still running some tests to make sure everything works as intended. Changing the coordinate system for coverage calculation turned into a rabbit hole of other things to adjust.

**Comment by ccchyn** [comment]
Hi Tamara,

I have tested the updates in the develop branch on a few cases and they worked well! I will run them on my remaining samples - will let you know if any issues pop up. 

thanks again for this!

Chyn

**Comment by tjblaette** [comment]
Oh I'm so glad! It's also passed all tests on my side now, so I'll push it up to the main branch. Please let me know if it does not work for you though!

**Comment by tjblaette** [comment]
Hi Chyn, 

just a heads up: I added another update to plot some coverage stats. Considering that your assay is slightly different from ours, it might be worth plotting the coverage for your samples to make sure it looks as expected. As I cannot test on mac myself right now, I would also be curious to know if it works for you with the current version. (Needs matplotlib installed plus `-plot_coverage True`. There will be `coverage.png` in the sample's output folder then.)

All the best,
Tamara

**Comment by ccchyn** [comment]
Dear Tamara,

I have just run the latest code on all my samples with great success! 
The coverage seemed good too with your additional update.  
Thanks again for your amazing pipeline. 
Take care!

Chyn

**Comment by tjblaette** [comment]
Hi Chyn,

That's great to hear, thank you so much for sharing the good news!

Stay safe,
Tamara
